import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../core/config.dart';
import '../../core/providers.dart';
import '../../data/models/candidate_project.dart';

class RecommendationScreen extends ConsumerWidget {
  const RecommendationScreen({
    super.key,
    required this.selected,
    required this.totalCost,
    required this.totalBeneficiaries,
    required this.budget,
    required this.equityEnabled,
  });

  final List<CandidateProject> selected;
  final int totalCost;
  final int totalBeneficiaries;
  final int budget;
  final bool equityEnabled;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final region = ref.watch(appRegionProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Recommendation Letter'),
        actions: [
          IconButton(
            icon: const Icon(Icons.print),
            tooltip: 'Print / Save PDF',
            onPressed: () => _printPdf(region),
          ),
          IconButton(
            icon: const Icon(Icons.share),
            tooltip: 'Share PDF',
            onPressed: () => _sharePdf(region),
          ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: PdfPreview(
              build: (_) => _generatePdf(region),
              canChangeOrientation: false,
              canChangePageFormat: false,
              canDebug: false,
              pdfFileName: 'ANTAR_Recommendation_${DateTime.now().millisecondsSinceEpoch}.pdf',
            ),
          ),
        ],
      ),
    );
  }

  Future<void> _printPdf(AppRegion region) async {
    final doc = await _generatePdf(region);
    await Printing.layoutPdf(onLayout: (_) async => doc);
  }

  Future<void> _sharePdf(AppRegion region) async {
    final doc = await _generatePdf(region);
    await Printing.sharePdf(
      bytes: doc,
      filename: 'ANTAR_Recommendation.pdf',
    );
  }

  Future<Uint8List> _generatePdf(AppRegion region) async {
    final pdf = pw.Document();
    final currencySymbol = region == AppRegion.brazil ? 'R\$' : '₹';
    final constituency =
        region == AppRegion.brazil ? 'São Paulo' : 'Varanasi';

    final fundHints = _fundHintsMap;

    // Group by category
    final byCategory = <String, List<CandidateProject>>{};
    for (final c in selected) {
      byCategory.putIfAbsent(c.category, () => []).add(c);
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _pdfHeader(constituency),
        footer: (context) => _pdfFooter(context),
        build: (context) => [
          // Title
          pw.Header(
            level: 0,
            child: pw.Text(
              'Priority Infrastructure Recommendation',
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            'Generated by ANTAR — AI for Digital Public Infrastructure & Governance',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
          ),
          pw.Text(
            'Date: ${_formatDate(DateTime.now())}',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 16),

          // Summary box
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey400),
              borderRadius: pw.BorderRadius.circular(4),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Executive Summary',
                  style: pw.TextStyle(
                    fontSize: 14,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 8),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    _summaryItem('Total Projects', '${selected.length}'),
                    _summaryItem(
                        'Total Cost', '$currencySymbol ${_formatAmount(totalCost, region)}'),
                    _summaryItem('Budget',
                        '$currencySymbol ${_formatAmount(budget, region)}'),
                    _summaryItem(
                        'Beneficiaries', _compactNumber(totalBeneficiaries)),
                  ],
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  equityEnabled
                      ? 'Equity boost enabled — silent-gap villages weighted +30%'
                      : 'Standard optimization — no equity adjustment',
                  style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 20),

          // Per-category sections
          for (final entry in byCategory.entries) ...[
            pw.Header(
              level: 1,
              child: pw.Row(
                children: [
                  pw.Text(
                    _categoryTitle(entry.key),
                    style: pw.TextStyle(
                      fontSize: 14,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(width: 8),
                  pw.Text(
                    '(${entry.value.length} projects)',
                    style: const pw.TextStyle(
                        fontSize: 10, color: PdfColors.grey600),
                  ),
                ],
              ),
            ),
            // Fund hint
            if (fundHints.containsKey(entry.key))
              pw.Container(
                margin: const pw.EdgeInsets.only(bottom: 8),
                padding: const pw.EdgeInsets.all(6),
                decoration: pw.BoxDecoration(
                  color: PdfColors.blue50,
                  borderRadius: pw.BorderRadius.circular(2),
                ),
                child: pw.Text(
                  'Fund convergence: ${fundHints[entry.key]!['scheme']} — ${fundHints[entry.key]!['note']}',
                  style: const pw.TextStyle(fontSize: 9, color: PdfColors.blue800),
                ),
              ),
            // Projects table
            pw.TableHelper.fromTextArray(
              headerStyle: pw.TextStyle(
                fontSize: 9,
                fontWeight: pw.FontWeight.bold,
              ),
              cellStyle: const pw.TextStyle(fontSize: 9),
              cellAlignments: {
                0: pw.Alignment.centerLeft,
                1: pw.Alignment.centerLeft,
                2: pw.Alignment.centerLeft,
                3: pw.Alignment.centerRight,
                4: pw.Alignment.centerRight,
                5: pw.Alignment.center,
              },
              headers: [
                'Project',
                'Village',
                'Block',
                'Cost ($currencySymbol)',
                'Beneficiaries',
                'Priority',
              ],
              data: entry.value
                  .map((c) => [
                        c.projectLabel,
                        c.villageName,
                        c.block,
                        _formatAmount(c.indicativeCost, region),
                        '${c.beneficiaries}',
                        c.priority.toStringAsFixed(2),
                      ])
                  .toList(),
            ),
            pw.SizedBox(height: 12),
          ],

        ],
      ),
    );

    return Uint8List.fromList(await pdf.save());
  }

  pw.Widget _pdfHeader(String constituency) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 12),
      padding: const pw.EdgeInsets.only(bottom: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: PdfColors.grey300, width: 1),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'ANTAR',
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.indigo800,
            ),
          ),
          pw.Text(
            constituency,
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
          ),
        ],
      ),
    );
  }

  pw.Widget _pdfFooter(pw.Context context) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 8),
      padding: const pw.EdgeInsets.only(top: 4),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          top: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'ANTAR — AI for Digital Public Infrastructure & Governance',
            style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey500),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey500),
          ),
        ],
      ),
    );
  }

  pw.Widget _summaryItem(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 14,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.indigo800,
          ),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          label,
          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
        ),
      ],
    );
  }

  String _formatDate(DateTime date) {
    const months = [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
    ];
    return '${date.day} ${months[date.month - 1]} ${date.year}';
  }

  String _formatAmount(int amount, AppRegion region) {
    if (region == AppRegion.brazil) {
      if (amount >= 1000000) return '${(amount / 1000000).toStringAsFixed(1)}M';
      if (amount >= 1000) return '${(amount / 1000).toStringAsFixed(0)}k';
      return '$amount';
    }
    if (amount >= 10000000) {
      return '${(amount / 10000000).toStringAsFixed(1)} Cr';
    }
    if (amount >= 100000) {
      return '${(amount / 100000).toStringAsFixed(1)} L';
    }
    return '$amount';
  }

  String _compactNumber(int n) {
    if (n >= 1000000) return '${(n / 1000000).toStringAsFixed(1)}M';
    if (n >= 1000) return '${(n / 1000).toStringAsFixed(1)}k';
    return '$n';
  }

  String _categoryTitle(String cat) {
    return switch (cat) {
      'road' => 'Road & Connectivity',
      'water' => 'Water Supply',
      'sanitation' => 'Sanitation',
      'electricity' => 'Electrification',
      'health' => 'Healthcare',
      'education' => 'Education',
      'internet' => 'Internet Connectivity',
      'banking' => 'Financial Inclusion',
      'transport' => 'Public Transport',
      _ => cat[0].toUpperCase() + cat.substring(1),
    };
  }

  Map<String, Map<String, String>> get _fundHintsMap => {
        'road': {
          'scheme': 'PMGSY (Pradhan Mantri Gram Sadak Yojana)',
          'note': 'Possible source — verify eligibility',
        },
        'water': {
          'scheme': 'Jal Jeevan Mission',
          'note': 'Possible source — verify eligibility',
        },
        'sanitation': {
          'scheme': 'Swachh Bharat Mission (Gramin)',
          'note': 'Possible source — verify eligibility',
        },
        'electricity': {
          'scheme': 'DDUGJY / Saubhagya',
          'note': 'Possible source — verify eligibility',
        },
        'health': {
          'scheme': 'National Health Mission (NHM)',
          'note': 'Possible source — verify eligibility',
        },
        'education': {
          'scheme': 'Samagra Shiksha Abhiyan',
          'note': 'Possible source — verify eligibility',
        },
        'internet': {
          'scheme': 'BharatNet',
          'note': 'Possible source — verify eligibility',
        },
        'banking': {
          'scheme': 'PMJDY / Financial Inclusion',
          'note': 'Possible source — verify eligibility',
        },
        'transport': {
          'scheme': 'MPLADS / State Transport Fund',
          'note': 'Possible source — verify eligibility',
        },
      };
}
